<?php header('Content-Type: text/html; charset=UTF-8'); ?>
<?= $this->doctype() ?>

<html lang="de">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Ro-Community')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-rocom navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        Ro-Community
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <?= $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav'); ?>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="#">
                                <i class="fa fa-users" aria-hidden="true"></i> <span class="nav-badge">1</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-bell" aria-hidden="true"></i> <span class="nav-badge">3</span>
                            </a>  
                        </li>
                        <li>    
                            <a href="#">    
                                <i class="fa fa-envelope" aria-hidden="true"></i> <span class="nav-badge">5</span> 
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-user" aria-hidden="true"></i> Unreality <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#"><i class="fa fa-user"></i> Profil</a></li>
                                <li><a href="#"><i class="fa fa-cog"></i> Einstellungen</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#"><i class="fa fa-sign-out"></i> Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> Ro-Community</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
