<?php $this->headTitle($title); ?>
<h2>Development Tagebuch</h2>

<?php foreach ($news as $entry) : ?>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $entry->title ?></h3>
            </div>
            <div class="panel-body">
                <?= $entry->content ?>
            </div>
            <div class="panel-footer">
                <i><?= $entry->author ?> - <?= date('d.m.Y', strtotime($entry->datetime)) ?></i>
            </div>
        </div>        
    </div>
</div>

<?php endforeach; ?>